//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCalc.Domain.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommercialPlanRange
    {
        public int idPlanrange { get; set; }
        public Nullable<int> startRange { get; set; }
        public Nullable<int> endRange { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> idCommercialplan { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
    
        public virtual CommercialPlan CommercialPlan { get; set; }
    }
}
