//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCalc.Domain.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.ExecutionLog = new HashSet<ExecutionLog>();
        }
    
        public int idCustomer { get; set; }
        public string ruc { get; set; }
        public string legalName { get; set; }
        public Nullable<int> idCommercialplan { get; set; }
        public Nullable<int> idPlantype { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
    
        public virtual CommercialPlan CommercialPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutionLog> ExecutionLog { get; set; }
    }
}
