//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCalc.Domain.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionLog
    {
        public int idExecutionlog { get; set; }
        public Nullable<int> idCustomer { get; set; }
        public Nullable<int> transactionsCount { get; set; }
        public Nullable<decimal> totalCalc { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public string status { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
