//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCalc.Domain.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanType()
        {
            this.CommercialPlan = new HashSet<CommercialPlan>();
        }
    
        public int idPlantype { get; set; }
        public string name { get; set; }
        public Nullable<bool> requireRange { get; set; }
        public Nullable<bool> isDynamic { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommercialPlan> CommercialPlan { get; set; }
    }
}
