//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fcalc.Infra.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using FCalc.Domain.Model.Entities;
    
    public partial class FcalcDBEntities1 : DbContext
    {
        public FcalcDBEntities1()
            : base("name=FcalcDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommercialPlan> CommercialPlan { get; set; }
        public virtual DbSet<CommercialPlanRange> CommercialPlanRange { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<ExecutionLog> ExecutionLog { get; set; }
        public virtual DbSet<PlanType> PlanType { get; set; }
    }
}
